name: Prebuild Vercel Tutor

on: push

jobs:
  clone-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: |
          node --version
          npm --version

      - run: |
          npm install -g vercel@latest
          vc --version

      - working-directory: ./vercel-tutor
        run: |
          corepack enable
          pnpm install
        env:
          NPM_CONFIG_LOGLEVEL: http

      - working-directory: ./vercel-tutor
        run: |
          vc build --debug --token $VERCEL_TOKEN --yes --prod
        env:
          VERCEL_PROJECT_ID: prj_MOlShEFPtl2m22AhKxjXZYUbnsRX
          VERCEL_TOKEN: ${{ secrets.VERCEL_EXAMPLES_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_EXAMPLES_ORG_ID }}

      - working-directory: ./examples/nextjs
        run: |
          vc deploy --debug --token $VERCEL_TOKEN --yes --prod --prebuilt --archive=tgz
        env:
          VERCEL_PROJECT_ID: prj_MOlShEFPtl2m22AhKxjXZYUbnsRX
          VERCEL_TOKEN: ${{ secrets.VERCEL_EXAMPLES_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_EXAMPLES_ORG_ID }}