name: Playwright

on:
  schedule:
    # Runs at the minute 15 of every hour
    - cron: '15 0/1 * * *'

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: vercel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  run:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.26.0-focal
      # Prevents the image from getting into permission denied errors
      options: --user 1001
    defaults:
      run:
        shell: bash
        working-directory: internal
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.2.0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: Generate E2E tests
        run: pnpm build --filter=@vercel/playwright

      - name: Run E2E tests
        run: pnpm test --filter=@vercel/playwright

      - name: Upload test results to GitHub
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: playwright-E2E-report
          path: internal/packages/playwright/src/test-results
