name: Release @vercel/examples-ui

on: push

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: vercel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: internal
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.12.1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Create Release PR or Publish Packages
        uses: changesets/action@v1
        with:
          # Builds the package and executes `changeset publish`
          publish: pwd && cd internal && pnpm release
          # Alias to `changeset version` script in package.json
          version: pwd && cd internal && pnpm version-packages
          commit: 'chore: update package versions'
          title: 'chore: update package versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
